from pathlib import Path


def create_directories(root: Path, folders: list[str]) -> None:
    for folder in folders:
        target = root / folder
        target.mkdir(parents=True, exist_ok=True)
        print(f"Created directory: {target}")


def create_file(root: Path, relative_path: str, content: str = "") -> None:
    file_path = root / relative_path
    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text(content, encoding="utf-8")
    print(f"Created file: {file_path}")


if __name__ == "__main__":
    project_root = Path(__file__).resolve().parent

    folders = [
        "client/src/app",
        "client/src/assets",
        "client/src/components/common",
        "client/src/features/auth",
        "client/src/hooks",
        "client/src/pages/About",
        "client/src/pages/Authentication",
        "client/src/pages/Contact",
        "client/src/pages/Home",
        "client/src/pages/Projects",
        "client/src/pages/Skills",
        "client/src/pages/Technologies",
        "client/src/redux/slices",
        "client/src/routes",
        "client/src/services",
        "client/src/styles",
        "client/src/utils",
        "public/hdri",
        "public/models/fruits",
        "server/src/config",
        "server/src/controllers",
        "server/src/middleware",
        "server/src/models",
        "server/src/routes",
        "server/src/services",
        "server/src/utils",
    ]

    create_directories(project_root, [
        "client",
        "client/src",
        "client/src/components",
        "client/src/features",
        "client/src/pages",
        "client/src/redux",
        "public",
        "server",
        "server/src",
    ])
    create_directories(project_root, folders)

    files = {
        "index.html": """<!doctype html>
<html lang=\"en\">
  <head>
    <meta charset=\"UTF-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
    <title>Portfolio</title>
  </head>
  <body>
    <div id=\"root\"></div>
    <script type=\"module\" src=\"/src/main.jsx\"></script>
  </body>
</html>
""",
        "README.md": """# Portfolio Project

This project was generated by a Python folder structure script.

## Running locally

```bash
npm install
npm run dev
```
""",
        "client/src/main.jsx": """import ReactDom from 'react-dom/client';
import App from './App';
import AppProvider from './app/provider';
import AuthInitializer from './components/common/AuthInitializer';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/js/bootstrap.bundle.min.js';
import './index.css';

ReactDom.createRoot(document.getElementById('root')).render(
  <AppProvider>
    <AuthInitializer>
      <App />
    </AuthInitializer>
  </AppProvider>
);
""",
        "client/src/App.jsx": """import './App.css';
import AppRoutes from './routes/AppRoutes';

function App() {
  return <AppRoutes />;
}

export default App;
""",
        "client/src/App.css": """body {
  margin: 0;
  font-family: Arial, sans-serif;
  background: #111827;
  color: white;
}
""",
        "client/src/index.css": """* {
  box-sizing: border-box;
}

html, body, #root {
  margin: 0;
  min-height: 100%;
  height: 100%;
}
""",
        "client/src/app/provider.jsx": """import { Provider } from 'react-redux';
import store from './store';

function AppProvider({ children }) {
  return <Provider store={store}>{children}</Provider>;
}

export default AppProvider;
""",
        "client/src/app/rootReducer.js": """const rootReducer = (state = {}, action) => state;

export default rootReducer;
""",
        "client/src/app/store.js": """import { configureStore } from '@reduxjs/toolkit';
import rootReducer from './rootReducer';

const store = configureStore({
  reducer: rootReducer,
});

export default store;
""",
        "client/src/components/common/AuthInitializer.jsx": """function AuthInitializer({ children }) {
  return <>{children}</>;
}

export default AuthInitializer;
""",
        "client/src/components/common/Button.jsx": """function Button({ children, ...props }) {
  return <button {...props}>{children}</button>;
}


export default Layout;
""",
        "client/src/components/layout/PageFooter.jsx": """function PageFooter() {
  return <footer>Footer</footer>;
}

export default PageFooter;
""",
        "client/src/features/auth/authAPI.js": """export const authAPI = {};
""",
        "client/src/features/auth/authService.js": """export const authService = {};
""",
        "client/src/features/auth/authSlice.js": """export const authSlice = {};
""",

        "client/src/hooks/useAppDispatch.js": """export default function useAppDispatch() {
  return () => {};
}
""",

        "client/src/pages/About/About.css": """/* About page styles */
""",
        "client/src/pages/About/About.jsx": """function About() {
  return <div>About</div>;
}

export default About;
""",
        "client/src/pages/Authentication/Login.jsx": """function Login() {
  return <div>Login</div>;
}

export default Login;
""",
        "client/src/pages/Authentication/Register.jsx": """function Register() {
  return <div>Register</div>;
}

export default Register;
""",
        "client/src/pages/Contact/Contact.jsx": """function Contact() {
  return <div>Contact</div>;
}

export default Contact;
""",
        "client/src/pages/Home/Home.css": """/* Home styles */
""",
        "client/src/pages/Home/Home.jsx": """function Home() {
  return <div>Home</div>;
}

export default Home;
""",
        "client/src/pages/Projects/Projects.jsx": """function Projects() {
  return <div>Projects</div>;
}

export default Projects;
""",
        "client/src/pages/Skills/Skills.jsx": """function Skills() {
  return <div>Skills</div>;
}

export default Skills;
""",
        "client/src/pages/Technologies/Technologies.jsx": """function Technologies() {
  return <div>Technologies</div>;
}

export default Technologies;
""",
        "client/src/routes/AppRoutes.jsx": """import { BrowserRouter, Routes, Route } from 'react-router-dom';
import Home from '../pages/Home/Home';
import About from '../pages/About/About';
import Skills from '../pages/Skills/Skills';
import Projects from '../pages/Projects/Projects';
import Contact from '../pages/Contact/Contact';

function AppRoutes() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path=\"/\" element={<Home />} />
        <Route path=\"/about\" elementcom={<About />} />
        <Route path=\"/skills\" element={<Skills />} />
        <Route path=\"/projects\" element={<Projects />} />
        <Route path=\"/contact\" element={<Contact />} />
      </Routes>
    </BrowserRouter>
  );
}

export default AppRoutes;
""",
        "client/src/routes/ProtectedRoute.jsx": """function ProtectedRoute({ children }) {
  return <>{children}</>;
}

export default ProtectedRoute;
""",
        "client/src/routes/PublicRoute.jsx": """function PublicRoute({ children }) {
  return <>{children}</>;
}

export default PublicRoute;
""",


        "server/package.json": """{
  \"name\": \"portfolio-server\",
  \"version\": \"1.0.0\",
  \"main\": \"src/server.js\",
  \"scripts\": {
    \"start\": \"node src/server.js\",
    \"dev\": \"nodemon src/server.js\"
  },
  \"dependencies\": {
    \"bcryptjs\": \"^2.4.3\",
    \"cors\": \"^2.8.5\",
    \"dotenv\": \"^16.4.5\",
    \"express\": \"^4.21.1\",
    \"jsonwebtoken\": \"^9.0.2\",
    \"mongoose\": \"^8.8.1\"
  },
  \"devDependencies\": {
    \"nodemon\": \"^3.1.0\"
  }
}
""",
        "server/src/app.js": """const express = require('express');
const cors = require('cors');

const app = express();

app.use(cors());
app.use(express.json());

app.get('/', (req, res) => {
  res.json({ message: 'Portfolio server is running' });
});

module.exports = app;
""",
        "server/src/server.js": """require('dotenv').config();
const app = require('./app');

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
""",
        "server/src/config/db.js": """const mongoose = require('mongoose');

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/portfolio');
    console.log('MongoDB connected');
  } catch (error) {
    console.error('MongoDB connection failed:', error.message);
    process.exit(1);
  }
};

module.exports = connectDB;
""",
        "server/src/controllers/authController.js": """const authService = require('../services/authService');

exports.register = async (req, res) => {
  res.json({ message: 'Register endpoint' });
};

exports.login = async (req, res) => {
  res.json({ message: 'Login endpoint' });
};
""",
        "server/src/middleware/authMiddelware.js": """const authMiddleware = (req, res, next) => {
  next();
};

module.exports = authMiddleware;
""",
        "server/src/models/User.js": """const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  name: String,
  email: String,
  password: String,
});

module.exports = mongoose.model('User', userSchema);
""",
        "server/src/routes/authRoutes.js": """const express = require('express');
const { register, login } = require('../controllers/authController');

const router = express.Router();

router.post('/register', register);
router.post('/login', login);

module.exports = router;
""",
        "server/src/services/authService.js": """const User = require('../models/User');

const authService = {
  register: async () => ({ message: 'user created' }),
  login: async () => ({ message: 'logged in' }),
};

module.exports = authService;
""",
        "server/src/utils/generateToken.js": """const jwt = require('jsonwebtoken');

const generateToken = (userId) => jwt.sign({ id: userId }, process.env.JWT_SECRET || 'secret', {
  expiresIn: '7d',
});

module.exports = generateToken;
""",
    }

    for relative_path, content in files.items():
        create_file(project_root, relative_path, content)

    print(f"\nProject structure ready under: {project_root}")
